version: "3.1"

services:
  db:
    container_name: DatabasePractise
    image: postgres:12
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 5433:5432
